=== dwsteele/pg_backrest/doc/xml/dtd/doc.dtd
<!ELEMENT doc ((intro, changelog)|(config, operation)|(description, variable-list?, cleanup?, section+))>
    <!ATTLIST doc title CDATA "">
    <!ATTLIST doc subtitle CDATA "">
    <!ATTLIST doc toc CDATA "y">

<!ELEMENT description (#PCDATA)>

<!ELEMENT intro (text)>

<!ELEMENT operation (description, text?, operation-general, command-list)>
    <!ATTLIST operation title CDATA #REQUIRED>

<!ELEMENT operation-general (option-list)>
    <!ATTLIST operation-general title CDATA #REQUIRED>

<!ELEMENT command-list (text?, command+)>
    <!ATTLIST command-list title CDATA #REQUIRED>

<!ELEMENT command (summary, text, option-list?, command-example-list)>
    <!ATTLIST command id CDATA #REQUIRED>
    <!ATTLIST command name CDATA #REQUIRED>

<!ELEMENT command-example-list (text?, command-example+)>
    <!ATTLIST command-example-list title CDATA "Examples">

<!ELEMENT command-example (text)>
    <!ATTLIST command-example title CDATA "Example">

<!ELEMENT option-list (option+)>

<!ELEMENT option (summary, text, example)>
    <!ATTLIST option id CDATA #REQUIRED>
    <!ATTLIST option name CDATA #REQUIRED>

<!ELEMENT config (description, text, config-section-list)>
    <!ATTLIST config title CDATA #REQUIRED>

<!ELEMENT config-example (text)>
    <!ATTLIST config-example title CDATA #REQUIRED>

<!ELEMENT config-section-list (text?, config-section+)>
    <!ATTLIST config-section-list title CDATA #REQUIRED>

<!ELEMENT config-section (text, config-key-list?)>
    <!ATTLIST config-section id CDATA #REQUIRED>
    <!ATTLIST config-section name CDATA #REQUIRED>

<!ELEMENT config-key-list (config-key+)>

<!ELEMENT config-key (summary, text, default?, allow?, example)>
    <!ATTLIST config-key id CDATA #REQUIRED>
    <!ATTLIST config-key name CDATA #REQUIRED>

<!ELEMENT execute-list (title, execute+)>
    <!ATTLIST execute-list host CDATA #REQUIRED>
    <!ATTLIST execute-list keyword CDATA "">
<!ELEMENT execute (exe-cmd, exe-user?,  exe-var?, exe-retry?, exe-output?, (exe-highlight-type?, exe-highlight)?,
                   exe-err-expect?, exe-err-suppress?, exe-err-suppress-stderr?)>
    <!ATTLIST execute keyword CDATA "">
    <!ATTLIST execute user CDATA "">
    <!ATTLIST execute filter CDATA "">
    <!ATTLIST execute filter-context CDATA "">
    <!ATTLIST execute skip CDATA "">
    <!ATTLIST execute show CDATA "">
    <!ATTLIST execute output CDATA "">
    <!ATTLIST execute err-suppress CDATA "">
    <!ATTLIST execute err-expect CDATA "">
    <!ATTLIST execute retry CDATA "">
    <!ATTLIST execute variable-key CDATA "">
<!ELEMENT exe-cmd (#PCDATA)>
<!ELEMENT exe-highlight (#PCDATA)>
<!ELEMENT exe-highlight-type (#PCDATA)>

<!ELEMENT cleanup (execute+)>

<!ELEMENT variable-list (variable+)>
<!ELEMENT variable (#PCDATA)>
    <!ATTLIST variable key CDATA #REQUIRED>
    <!ATTLIST variable keyword CDATA "default">
    <!ATTLIST variable eval CDATA "n">

<!ELEMENT backrest-config (title, backrest-config-option+)>
    <!ATTLIST backrest-config host CDATA #REQUIRED>
    <!ATTLIST backrest-config owner CDATA "">
    <!ATTLIST backrest-config show CDATA "">
    <!ATTLIST backrest-config keyword CDATA "">
    <!ATTLIST backrest-config reset CDATA "">
    <!ATTLIST backrest-config file CDATA #REQUIRED>
<!ELEMENT backrest-config-option (#PCDATA)>
    <!ATTLIST backrest-config-option keyword CDATA "">
    <!ATTLIST backrest-config-option section CDATA #REQUIRED>
    <!ATTLIST backrest-config-option key CDATA #REQUIRED>
    <!ATTLIST backrest-config-option remove CDATA "n">

<!ELEMENT postgres-config (title, postgres-config-option+)>
    <!ATTLIST postgres-config host CDATA #REQUIRED>
    <!ATTLIST postgres-config file CDATA #REQUIRED>
    <!ATTLIST postgres-config keyword CDATA "">
    <!ATTLIST postgres-config show CDATA "">
<!ELEMENT postgres-config-option (#PCDATA)>
    <!ATTLIST postgres-config-option keyword CDATA "">
    <!ATTLIST postgres-config-option key CDATA #REQUIRED>

<!ELEMENT option-description EMPTY>
    <!ATTLIST option-description key CDATA #REQUIRED>

<!ELEMENT section (title,
                   ((p|table|host-add|execute-list|backrest-config|postgres-config|option-description|code-block)+|
                   (p*, section+)|p*))>
    <!ATTLIST section id CDATA #REQUIRED>
    <!ATTLIST section keyword CDATA "">
    <!ATTLIST section depend CDATA "">
<!ELEMENT title (#PCDATA|b|i|bi|ul|ol|id|code|file|path|cmd|param|setting|exe|backrest|postgres|br-option|br-setting|
                 pg-option|pg-setting|link|user)*>

<!ELEMENT default (#PCDATA)>
<!ELEMENT allow (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!ELEMENT changelog (text?, changelog-release+)>

<!ELEMENT changelog-release (text?, release-feature-bullet-list)>
    <!ATTLIST changelog-release date CDATA #REQUIRED>
    <!ATTLIST changelog-release version CDATA #REQUIRED>
    <!ATTLIST changelog-release title CDATA #REQUIRED>

<!ELEMENT release-feature-bullet-list (release-feature+)>

<!ELEMENT release-feature (text)>

<!ELEMENT contribute (text)>
    <!ATTLIST contribute title CDATA #REQUIRED>

<!ELEMENT recognition (text)>
    <!ATTLIST recognition title CDATA #REQUIRED>

<!ELEMENT support (text)>
    <!ATTLIST support title CDATA #REQUIRED>

<!-- Host elements -->
<!ELEMENT host-add (execute*)>
    <!ATTLIST host-add name CDATA #REQUIRED>
    <!ATTLIST host-add user CDATA #REQUIRED>
    <!ATTLIST host-add image CDATA #REQUIRED>
    <!ATTLIST host-add os CDATA "">
    <!ATTLIST host-add mount CDATA "">

<!-- Table elements -->
<!ELEMENT table (title?, table-header, table-data)>

<!ELEMENT table-header (table-column+)>
    <!ATTLIST table-header width CDATA "">
<!ELEMENT table-column (#PCDATA|quote|b|i|id|code|host|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                        br-setting|pg-option|pg-setting|link|user)*>
    <!ATTLIST table-column align CDATA "">
    <!ATTLIST table-column fill CDATA "">

<!ELEMENT table-data (table-row+)>
<!ELEMENT table-row (table-cell+)>
<!ELEMENT table-cell (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                      br-setting|pg-option|pg-setting|link|user)*>

<!-- Formatted elements -->
<!ELEMENT summary (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                   br-setting|pg-option|pg-setting|link|user)*>
<!ELEMENT p (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|param|setting|exe|backrest|postgres|br-option|br-setting|
             pg-option|pg-setting|link|user)*>
    <!ATTLIST p keyword CDATA "">
<!ELEMENT text (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                br-setting|pg-option|pg-setting|link|user)*>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT li (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
              br-setting|pg-option|pg-setting|link|user)*>
<!ELEMENT id (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT code-block (#PCDATA|exe)*>
    <!ATTLIST code-block title CDATA #REQUIRED>

<!ELEMENT host (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT cmd (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT br-option (#PCDATA)>
<!ELEMENT br-setting (#PCDATA)>
<!ELEMENT pg-option (#PCDATA)>
<!ELEMENT pg-setting (#PCDATA)>
<!ELEMENT exe EMPTY>
<!ELEMENT backrest EMPTY>
<!ELEMENT postgres EMPTY>
<!ELEMENT link (#PCDATA)>
    <!ATTLIST link url CDATA "">
    <!ATTLIST link page CDATA "">
    <!ATTLIST link section CDATA "">

=== dwsteele/pg_backrest/doc/xml/coding.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc title="{[project]}" subtitle="Coding Standards" toc="y">
    <description>{[project]} Coding Standard.</description>

    <section id="standards">
        <title>Standards</title>

        <section id="indentation">
            <title>Indentation</title>

            <p>Indentation is four spaces -- no tabs.  Only file types that absolutely require tabs (e.g. `Makefile`) may use them.</p>
        </section>

        <section id="naming">
            <title>Naming</title>

            <section id="variables">
                <title>Variables</title>

                <p>Variable names use camel case with the first letter lower-case.</p>

                <list>
                    <list-item><id>stanzaName</id> - the name of the stanza</list-item>
                    <list-item><id>nameIdx</id> - loop variable for iterating through a list of names</list-item>
                </list>

                <p>Variable names should be descriptive.  Avoid <id>i</id>, <id>j</id>, etc.</p>
            </section>

            <section id="types">
                <title>Types</title>

                <p>Type names use camel case with the first letter upper case:

                <code>typedef struct MemContext &lt;...&gt;</code>

                <code>typedef enum {&lt;...&gt;} ErrorState;</code></p>
            </section>

            <section id="constants">
                <title>Constants</title>

                <p><b>#define Constants</b></p>

                <p><code>#define</code> constants should be all caps with <id>_</id> separators.</p>

                <code-block type="c">
#DEFINE MY_CONSTANT "STRING"
                </code-block>

                <p>The value should be aligned at column 69 whenever possible.</p>

                <p>This type of constant should mostly be used for strings.  Use enums whenever possible for integer constants.</p>

                <p><b>Enum Constants</b></p>

                <p>Enum elements follow the same case rules as variables. They are strongly typed so this shouldn't present any confusion.</p>

                <code-block type="c">
typedef enum
{
    cipherModeEncrypt,
    cipherModeDecrypt,
} CipherMode;
                </code-block>

                <p>Note the comma after the last element.  This reduces diff churn when new elements are added.</p>
            </section>

            <section id="macros">
                <title>Macros</title>

                <p>Macro names should be upper-case with underscores between words. Macros (except simple constants) should be avoided whenever possible as they make code less clear and test coverage harder to measure.</p>

                <p>Macros should follow the format:</p>

                <code-block type="c">
#define MACRO(paramName1, paramName2)   \
    &lt;code&gt;
                </code-block>

                <p>If the macro defines a block it should look like:</p>

                <code-block type="c">
#define MACRO_2(paramName1, paramName2) \
{                                       \
    &lt;code&gt;                              \
}
                </code-block>

                <p>Continuation characters should be aligned at column 132 (unlike the examples above that have been shortened for display purposes).</p>

                <p>To avoid conflicts, variables in a macro will be named <id>[macro name]_[var name]</id>, e.g. <id>TEST_RESULT_resultExpected</id>. Variables that need to be accessed in wrapped code should be provided accessor macros.</p>

                <p><link section="/language-elements/variadic-functions">Variadic functions</link> are an exception to the capitalization rule.</p>
            </section>

            <section id="begin-end">
                <title>Begin / End</title>

                <p>Use <id>Begin</id> / <id>End</id> for names rather than <id>Start</id> / <id>Finish</id>, etc.</p>
            </section>

            <section id="new-free">
                <title>New / Free</title>

                <p>Use <id>New</id> / <id>Free</id> for constructors and destructors rather than <id>Create</id> / <id>Destroy</id>, etc.</p>
            </section>
        </section>

        <section id="formatting">
            <title>Formatting</title>

            <section id="braces">
                <title>Braces</title>

                <p>C allows braces to be excluded for a single statement.  However, braces should be used when the control statement (if, while, etc.) spans more than one line or the statement to be executed spans more than one line.</p>

                <p>No braces needed:</p>

                <code-block type="c">
if (condition)
    return value;
                </code-block>

                <p>Braces needed:</p>

                <code-block type="c">
if (conditionThatUsesEntireLine1 &amp;&amp;
    conditionThatUsesEntireLine2)
{
    return value;
}
                </code-block>

                <code-block type="c">
if (condition)
{
    return
        valueThatUsesEntireLine1 &amp;&amp;
        valueThatUsesEntireLine2;
}
                </code-block>
            </section>
        </section>
    </section>

    <section id="language-elements">
        <title>Language Elements</title>

        <section id="data-types">
            <title>Data Types</title>

            <p>Don't get exotic - use the simplest type that will work.

            Use <id>int</id> or <id>unsigned int</id> for general cases. <id>int</id> will be at least 32 bits. When not using <id>int</id> use one of the types defined in <file>common/type.h</file>.</p>
        </section>

        <section id="macros">
            <title>Macros</title>

            <p>Don't use a macro when a function could be used instead.  Macros make it hard to measure code coverage.</p>
        </section>

        <section id="objects">
            <title>Objects</title>

            <p>Object-oriented programming is used extensively.  The object pointer is always referred to as <id>this</id>.</p>
        </section>

        <section id="variadic-functions">
            <title>Variadic Functions</title>

            <p>Variadic functions can take a variable number of parameters.  While the <code>printf()</code> pattern is variadic, it is not very flexible in terms of optional parameters given in any order.</p>

            <p>This project implements variadic functions using macros (which are exempt from the normal macro rule of being all caps).  A typical variadic function definition:</p>

            <code-block type="c">
typedef struct StoragePathCreateParam
{
    bool errorOnExists;
    bool noParentCreate;
    mode_t mode;
} StoragePathCreateParam;

#define storagePathCreateP(this, pathExp, ...)                              \
    storagePathCreate(this, pathExp, (StoragePathCreateParam){__VA_ARGS__})
#define storagePathCreateNP(this, pathExp)                                  \
    storagePathCreate(this, pathExp, (StoragePathCreateParam){0})

void storagePathCreate(const Storage *this, const String *pathExp, StoragePathCreateParam param);
            </code-block>

            <p>Continuation characters should be aligned at column 132 (unlike the example above that has been shortened for display purposes).</p>

            <p>This function can be called without variable parameters:</p>

            <code-block type="c">
storagePathCreateNP(storageLocal(), "/tmp/pgbackrest");
            </code-block>

            <p>Or with variable parameters:</p>

            <code-block type="c">
storagePathCreateP(storageLocal(), "/tmp/pgbackrest", .errorOnExists = true, .mode = 0777);
            </code-block>

            <p>If the majority of functions in a module or object are variadic it is best to provide macros for all functions even if they do not have variable parameters.  Do not use the base function when variadic macros exist.</p>
        </section>
    </section>

    <section id="testing">
        <title>Testing</title>

        <section id="uncoverable-uncovered">
            <title>Uncoverable/Uncovered Code</title>

            <section id="uncoverable">
                <title>Uncoverable Code</title>

                <p>The <id>uncoverable</id> keyword marks code that can never be covered.  For instance, a function that never returns because it always throws a error.  Uncoverable code should be rare to non-existent outside the common libraries and test code.</p>

                <code-block type="c">
}   // {uncoverable - function throws error so never returns}
                </code-block>

                <p>Subsequent code that is uncoverable for the same reason is marked with <code>// {+uncoverable}</code>.</p>
            </section>

            <section id="uncovered">
                <title>Uncovered Code</title>

                <p>Marks code that is not tested for one reason or another.  This should be kept to a minimum and an excuse given for each instance.</p>

                <code-block type="c">
exit(EXIT_FAILURE); // {uncovered - test harness does not support non-zero exit}
                </code-block>

                <p>Subsequent code that is uncovered for the same reason is marked with `// {+uncovered}`.</p>
            </section>
        </section>
    </section>
</doc>

=== dwsteele/pg_backrest/doc/xml/documentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc title="{[project]}" subtitle="Building Documentation" toc="y">
    <description>Building {[project]} Documentation</description>

    <section id="general">
        <title>General Builds</title>

        <p>The <backrest/> documentation can output a variety of formats and target several platforms and <postgres/> versions.</p>

        <p>This will build all documentation with defaults:</p>

        <code-block type="bash">
./doc.pl
        </code-block>

        <p>The user guide can be built for different platforms: <id>centos6</id>, <id>centos7</id>, and <id>debian</id>. This will build the HTML user guide for CentOS/RHEL 7:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --var=os-type=centos7
        </code-block>

        <p>Documentation generation will build a cache of all executed statements and use the cache to build the documentation quickly if no executed statements have changed.  This makes proofing text-only edits very fast, but sometimes it is useful to do a full build without using the cache:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --var=os-type=centos6 --no-cache
        </code-block>

        <p>Each <id>os-type</id> has a default container image that will be used as a base for creating hosts.  For <id>centos6</id>/<id>centos7</id> these defaults are generally fine, but for <id>debian</id> it can be useful to change the image.</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --var=os-type=debian --var=os-image=debian:9
        </code-block>
    </section>

    <section id="package">
        <title>Building with Packages</title>

        <p>A user-specified package can be used when building the documentation.  Since the documentation exercises most <backrest/> functionality this is a great way to smoke-test packages.</p>

        <p>The package must be located within the <backrest/> repo and the specified path should be relative to the repository base.  <path>test/package</path> is a good default path to use.</p>

        <p>Ubuntu 16.04:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --no-cache --var=os-type=debian --var=os-image=ubuntu:16.04 --var=package=test/package/pgbackrest_2.08-0_amd64.deb
        </code-block>

        <p>CentOS/RHEL 6:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --no-cache --var=os-type=centos6 --var=package=test/package/pgbackrest-2.08-1.el6.x86_64.rpm
        </code-block>

        <p>CentOS/RHEL 7:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --no-cache --var=os-type=centos7 --var=package=test/package/pgbackrest-2.08-1.el7.x86_64.rpm
        </code-block>

    </section>
</doc>

=== dwsteele/pg_backrest/doc/xml/contributing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc title="{[project]}" subtitle="Contributing to {[project]}" toc="y">
    <description>{[project]} Contributing Guidelines.</description>

    <section id="introduction">
        <title>Introduction</title>

        <p>This documentation is intended to assist contributors to <backrest/> by outlining some basic steps and guidelines for contributing to the project.  Coding standards to follow are defined in <link url="https://github.com/pgbackrest/pgbackrest/blob/master/CODING.md">CODING.md</link>. For testing, it is recommended that Vagrant and Docker be used; instructions are provided in the <file>README.md</file> file of the <backrest/> <link url="https://github.com/pgbackrest/pgbackrest/tree/master/test">test</link> directory. A list of all possible test combinations can be viewed by running:</p>
        <code-block>
            /backrest/test/test.pl --dry-run
        </code-block>

<!-- TODO:
1) Add the information on RHEL for testing since the XML parser is needed (see doc/README)
2) Also that readme explains building the docs so it may be usefull (if that info is not somewhere else) -->

    </section>

    <section id="option">
        <title>Adding an Option</title>

        <p>Options can be added to a command or multiple commands. Options can be configuration file only, command-line only or valid for both. Once an option is added, <file>config.auto.*</file>, <file>define.auto.*</file> and <file>parse.auto.*</file> files will automatically be generated by the build system.</p>

        <p> To add an option, two files need be to be modified:</p>
        <list>
            <list-item>build/lib/pgBackRestBuild/Config/Data.pm</list-item>
            <list-item>doc/xml/reference.xml</list-item>
        </list>

        <p>These files are discussed in the following sections.</p>

        <section id="data-file">
            <title>Data.pm</title>

            <p>There is a detailed comment at the top of this file on the configuration definitions which one can refer to in determining how to define the rules for the option.</p>

            <section id="command-line-only">
                <title>Command Line Only Options</title>

                <p>Command-line only options are options where <code>CFGDEF_SECTION</code> rule is not defined. There are two sections to be updated when adding a command-line only option, each of which is marked by the comment <code>Command-line only options</code>.</p>

                <list>
                    <list-item><b>Section 1:</b> Find the first section with the <code>Command-line only options</code> comment. This section defines and exports the constant for the actual option.</list-item>
                    <list-item><b>Section 2:</b> Find the second section with the <code>Command-line only options</code> comment. This is where the rules for the option are defined.</list-item>
                </list>

                <p>The steps for how to update these sections are detailed below.</p>

                <p><b>Section 1</b></p>

                <p>Copy the two lines (<quote>use constant</quote>/<quote>push</quote>) of an existing option and paste them where the option would be in alphabetical order and rename it to the same name as the new option name. For example CFGOPT_DRY_RUN, defined as <quote>dry-run</quote>.</p>

                <p><b>Section 2</b></p>

                <p>To better explain this section, <code>CFGOPT_ONLINE</code> will be used as an example:</p>

                <code-block>
    &amp;CFGOPT_ONLINE =>
    {
        &amp;CFGDEF_TYPE => CFGDEF_TYPE_BOOLEAN,
        &amp;CFGDEF_NEGATE => true,
        &amp;CFGDEF_DEFAULT => true,
        &amp;CFGDEF_COMMAND =>
        {
            &amp;CFGCMD_BACKUP => {},
            &amp;CFGCMD_STANZA_CREATE => {},
            &amp;CFGCMD_STANZA_UPGRADE => {},
        }
    },
                </code-block>

                <p>Note that <code>CFGDEF_SECTION</code> is not present thereby making this a command-line only option. Each line is explained below:</p>

                <list>
                    <list-item>CFGOPT_ONLINE - the name of the option as defined in <b>Section 1</b></list-item>
                    <list-item>CFGDEF_TYPE - the type of the option. Valid types are: <code>CFGDEF_TYPE_BOOLEAN</code>, <code>CFGDEF_TYPE_FLOAT</code>, <code>CFGDEF_TYPE_HASH</code>, <code>CFGDEF_TYPE_INTEGER</code>, <code>CFGDEF_TYPE_LIST</code>, <code>CFGDEF_TYPE_PATH</code>, <code>CFGDEF_TYPE_SIZE</code>, and <code>CFGDEF_TYPE_STRING</code>
                    </list-item>
                    <list-item>CFGDEF_NEGATE - being a command-line only boolean option, this rule would automatically default to false so it must be defined if the option is negatable. Ask yourself if negation makes sense, for example, would a --dry-run option make sense as --no-dry-run? If the answer is no, then this rule can be omitted as it would automatically default to false. Any boolean option that cannot be negatable, must be a command-line only and not a configuration file option as all configuration boolean options must be negatable.</list-item>
                    <list-item>CFGDEF_DEFAULT - sets a default for the option if the option is not provided when the command is run. The default can be global or it can be specified for a specific command in the <code>CFGDEF_COMMAND</code> section. For example, if it was desirable for the default to be false for the <code>CFGCMD_STANZA_CREATE</code> then CFGDEF_NEGATE =>  would be set to <code>true</code> in each command listed except for <code>CFGCMD_STANZA_CREATE</code> where it would be <code>false</code> and it would not be specified (as it is here) in the global section (meaning global for all commands listed).</list-item>
                    <list-item>CFGDEF_COMMAND - list each command for which the option is valid. If a command is not listed, then the option is not valid for the command and an error will be thrown if it attempted to be used for that command.</list-item>
                </list>

            </section>
        </section>

        <section id="reference-file">
            <title>reference.xml</title>
<!-- TODO: This info may be wrong - there are config- and option- sections so need to check. Also need to complete this sectino with examples-->
            <p>All options must be documented or the system will error during the build.  To add an option, find the command section identified by <code>config-section id="COMMAND"</code> section where COMMAND is the name of the command (e.g. <code>expire</code>) or, if the option is used by more than one command and the definition for the option is the same for all of the commands, the <code>config-section id="general"</code> section.</p>
        </section>
    </section>
</doc>

=== dwsteele/pg_backrest/doc/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc subtitle="Regression, Unit, &amp; Integration Testing" toc="y">
    <description>{[project]} testing configuration requirements, setup and options.</description>

    <section id="introduction">
        <title>Introduction</title>

        <p><backrest/> uses Docker to run tests and generate documentation.  Docker's light-weight virualization provides the a good balance between proper OS emulation and performance (especially startup)</p>

        <p>A `Vagrantfile` is provided that contains the complete configuration required to run <backrest/> tests and build documentation.  If Vagrant is not suitable then the `Vagrantfile` still contains the configuration steps required to build a test system.</p>

        <p>Note that this is not required for normal operation of <backrest/>.</p>
    </section>

    <section id="testing">
        <title>Testing</title>

        <p>The easiest way to start testing <backrest/> is with the included `Vagrantfile`.</p>

        <code-block title="Build Vagrant and Logon">
cd test
vagrant up
vagrant ssh
        </code-block>

        <p>The <code>vagrant up</code> command may take some time as a number of Docker containers must also be built.  The <code>vagrant ssh</code> command automatically logs onto the VM.</p>

        <code-block title="Run All Tests">
/backrest/test/test.pl
        </code-block>

        <code-block title="Run Tests for a Specific OS">
/backrest/test/test.pl --vm=co6
        </code-block>

        <code-block title="Run Tests for a Specific OS and Module">
/backrest/test/test.pl --vm=co6 --module=backup
        </code-block>

        <code-block title="Run Tests for a Specific OS, Module, and Test">
/backrest/test/test.pl --vm=co6 --module=backup --test=full
        </code-block>

        <code-block title="Run Tests for a Specific OS, Module, Test, and Run">
/backrest/test/test.pl --vm=co6 --module=backup --test=full --run=1
        </code-block>

        <code-block title="Run Tests for a Specific OS, Module, Test, and Thread Max">
/backrest/test/test.pl --vm=co6 --module=backup --test=full --thread-max=4
        </code-block>

        <p>Note that thread-max is only applicable to the <id>synthetic</id> and <id>full</id> tests in the <id>backup</id> module.</p>

        <code-block title="Run Tests for a Specific OS, Module, Test, Thread Max, and Database Version">
/backrest/test/test.pl --vm=co6 --module=backup --test=full --thread-max=4 --db-version=9.4
        </code-block>

        <p>Note that db-version is only applicable to the <id>full</id> test in the <id>backup</id> module.</p>

        <code-block title="Iterate All Possible Test Combinations">
/backrest/test/test.pl --dry-run
        </code-block>
    </section>
</doc>
